# Generated by Django 2.2.6 on 2019-11-18 19:36

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('mediamanagement', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='mediamanagemodel',
            old_name='content_path',
            new_name='body',
        ),
        migrations.RemoveField(
            model_name='mediamanagemodel',
            name='isdeleted',
        ),
        migrations.AlterField(
            model_name='mediamanagemodel',
            name='messageuuid',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='mediamanagemodel',
            name='uuid',
            field=models.TextField(default=uuid.UUID('842ec6ba-0a3a-11ea-abd1-645a049d591d')),
        ),
    ]
