# Generated by Django 2.2.6 on 2019-11-19 17:55

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('mediamanagement', '0002_auto_20191119_0106'),
    ]

    operations = [
        migrations.CreateModel(
            name='MediaFileModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='')),
            ],
        ),
        migrations.AlterField(
            model_name='mediamanagemodel',
            name='uuid',
            field=models.TextField(default=uuid.UUID('bd97c25c-0af5-11ea-8bf7-645a049d591d')),
        ),
    ]
