# Generated by Django 2.2.6 on 2019-11-19 20:27

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('mediamanagement', '0004_auto_20191119_2338'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mediamanagemodel',
            name='uuid',
            field=models.TextField(default=uuid.UUID('0ed8c6a2-0b0b-11ea-acb5-645a049d591d')),
        ),
    ]
