# Generated by Django 2.2.7 on 2019-11-20 12:02

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('mediamanagement', '0005_auto_20191120_0157'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mediamanagemodel',
            name='uuid',
            field=models.TextField(default=uuid.UUID('9367f436-0b8d-11ea-a0cc-c42c03361ed0')),
        ),
    ]
