# Generated by Django 2.2.7 on 2019-11-20 16:36

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('mediamanagement', '0006_auto_20191120_1202'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mediamanagemodel',
            name='uuid',
            field=models.TextField(default=uuid.UUID('e442fcdc-0bb3-11ea-96a3-645a049d591d')),
        ),
    ]
