# Generated by Django 2.2.6 on 2019-11-23 05:26

import django.core.files.storage
from django.db import migrations, models
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('mediamanagement', '0007_auto_20191120_2206'),
    ]

    operations = [
        migrations.CreateModel(
            name='MediaMessageModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.TextField(default=uuid.UUID('c25e3f46-0db1-11ea-b30a-645a049d591d'))),
                ('content_type', models.TextField()),
                ('filename', models.TextField()),
                ('phone', models.TextField()),
                ('body', models.TextField()),
                ('csv_file', models.FileField(upload_to='')),
                ('message_date_time', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.DeleteModel(
            name='MediaManageModel',
        ),
        migrations.AlterField(
            model_name='mediafilemodel',
            name='filepond',
            field=models.FileField(storage=django.core.files.storage.FileSystemStorage(location='/media/storage'), upload_to=''),
        ),
    ]
