# Generated by Django 2.2.6 on 2019-11-23 05:27

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('mediamanagement', '0008_auto_20191123_1056'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mediamessagemodel',
            name='uuid',
            field=models.TextField(default=uuid.UUID('ebb42992-0db1-11ea-83cb-645a049d591d')),
        ),
    ]
