# Generated by Django 2.2.6 on 2019-11-24 19:02

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('mediamanagement', '0011_auto_20191125_0017'),
    ]

    operations = [
        migrations.AddField(
            model_name='mediamessagemodel',
            name='caption',
            field=models.TextField(default='textt'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='mediamessagemodel',
            name='uuid',
            field=models.TextField(default=uuid.UUID('ee84a6c2-0eec-11ea-a61f-645a049d591d')),
        ),
    ]
