# Generated by Django 2.2.6 on 2019-11-27 18:28

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('mediamanagement', '0013_auto_20191127_2340'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mediamessagemodel',
            name='uuid',
            field=models.TextField(default=uuid.UUID('bc62adf4-1143-11ea-be5c-645a049d591d')),
        ),
    ]
