# Generated by Django 2.2.6 on 2019-11-27 18:31

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('mediamanagement', '0014_auto_20191127_2358'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mediamessagemodel',
            name='uuid',
            field=models.TextField(default=uuid.UUID('2342ac74-1144-11ea-bf37-645a049d591d')),
        ),
    ]
