# Generated by Django 2.2.6 on 2019-11-27 18:49

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('mediamanagement', '0015_auto_20191128_0001'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mediamessagemodel',
            name='uuid',
            field=models.TextField(default=uuid.UUID('9d6bb6a8-1146-11ea-9904-645a049d591d')),
        ),
    ]
