# Generated by Django 2.2.6 on 2019-11-27 18:57

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('mediamanagement', '0016_auto_20191128_0019'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mediamessagemodel',
            name='uuid',
            field=models.TextField(default=uuid.UUID('b5f0f8c6-1147-11ea-b706-645a049d591d')),
        ),
    ]
