# Generated by Django 2.2.6 on 2019-12-01 05:26

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('mediamanagement', '0018_auto_20191130_2213'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mediamessagemodel',
            name='uuid',
            field=models.TextField(default=uuid.UUID('25a0cf98-13fb-11ea-8656-645a049d591d')),
        ),
    ]
