# Generated by Django 2.2.6 on 2019-12-01 05:35

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('mediamanagement', '0019_auto_20191201_1056'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mediamessagemodel',
            name='uuid',
            field=models.TextField(default=uuid.UUID('5542e474-13fc-11ea-b6b2-645a049d591d')),
        ),
    ]
