# Generated by Django 2.2.6 on 2019-12-30 09:06

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('mediamanagement', '0021_auto_20191201_1118'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mediamessagemodel',
            name='uuid',
            field=models.TextField(default=uuid.UUID('a2b037d1-2ae3-11ea-a645-0a2555865e12')),
        ),
    ]
