# Generated by Django 2.2.6 on 2020-02-06 20:30

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('mediamanagement', '0022_auto_20191230_0906'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mediamessagemodel',
            name='uuid',
            field=models.TextField(default=uuid.UUID('8510f5ba-491f-11ea-99b0-645a049d591d')),
        ),
    ]
