# Generated by Django 2.2.6 on 2020-02-08 23:32

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('mediamanagement', '0023_auto_20200207_0200'),
    ]

    operations = [
        migrations.CreateModel(
            name='MultimediaCounter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('multimedia_message_count', models.BigIntegerField(default=0)),
            ],
        ),
        migrations.AlterField(
            model_name='mediamessagemodel',
            name='uuid',
            field=models.TextField(default=uuid.UUID('50629754-4acb-11ea-a9c3-645a049d591d')),
        ),
    ]
