# Generated by Django 2.2.6 on 2020-02-09 00:13

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('mediamanagement', '0024_auto_20200209_0502'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mediamessagemodel',
            name='uuid',
            field=models.TextField(default=uuid.UUID('fd6fab5e-4ad0-11ea-b77d-645a049d591d')),
        ),
    ]
