# Generated by Django 2.2.6 on 2020-02-09 00:29

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('mediamanagement', '0026_auto_20200209_0545'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mediamessagemodel',
            name='uuid',
            field=models.TextField(default=uuid.UUID('2cc00424-4ad3-11ea-8dbf-645a049d591d')),
        ),
    ]
