# Generated by Django 2.2.6 on 2020-02-09 00:30

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('mediamanagement', '0027_auto_20200209_0559'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mediamessagemodel',
            name='uuid',
            field=models.TextField(default=uuid.UUID('59f2375c-4ad3-11ea-a8f5-645a049d591d')),
        ),
    ]
