# Generated by Django 2.2.6 on 2020-02-09 00:31

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('mediamanagement', '0028_auto_20200209_0600'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mediamessagemodel',
            name='uuid',
            field=models.TextField(default=uuid.UUID('7e58e6c6-4ad3-11ea-9593-645a049d591d')),
        ),
    ]
