# Generated by Django 2.2.6 on 2020-02-09 00:32

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('mediamanagement', '0029_auto_20200209_0601'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mediamessagemodel',
            name='uuid',
            field=models.TextField(default=uuid.UUID('a79288c6-4ad3-11ea-bc73-645a049d591d')),
        ),
    ]
