# Generated by Django 2.2.6 on 2020-02-09 00:37

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('mediamanagement', '0031_auto_20200209_0603'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mediamessagemodel',
            name='uuid',
            field=models.TextField(default=uuid.UUID('64c9ac0a-4ad4-11ea-a2c8-645a049d591d')),
        ),
    ]
