# Generated by Django 2.2.6 on 2020-02-09 00:40

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('mediamanagement', '0033_auto_20200209_0609'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mediamessagemodel',
            name='uuid',
            field=models.TextField(default=uuid.UUID('c41f850c-4ad4-11ea-bc2f-645a049d591d')),
        ),
    ]
