# Generated by Django 2.2.6 on 2020-02-09 00:42

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('mediamanagement', '0035_auto_20200209_0611'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mediamessagemodel',
            name='uuid',
            field=models.TextField(default=uuid.UUID('0ccc1a2c-4ad5-11ea-a155-645a049d591d')),
        ),
    ]
