# Generated by Django 2.2.6 on 2020-02-09 00:42

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('mediamanagement', '0036_auto_20200209_0612'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mediamessagemodel',
            name='uuid',
            field=models.TextField(default=uuid.UUID('125a03f6-4ad5-11ea-aeea-645a049d591d')),
        ),
    ]
