# Generated by Django 2.2.6 on 2020-02-09 00:44

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('mediamanagement', '0037_auto_20200209_0612'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mediamessagemodel',
            name='uuid',
            field=models.TextField(default=uuid.UUID('4dfcabd8-4ad5-11ea-b7ce-645a049d591d')),
        ),
    ]
