# Generated by Django 2.2.6 on 2020-02-09 00:47

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('mediamanagement', '0038_auto_20200209_0614'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mediamessagemodel',
            name='uuid',
            field=models.TextField(default=uuid.UUID('bfd9e392-4ad5-11ea-9c19-645a049d591d')),
        ),
    ]
