# Generated by Django 2.2.6 on 2020-02-09 11:15

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('mediamanagement', '0040_auto_20200209_0621'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mediamessagemodel',
            name='uuid',
            field=models.TextField(default=uuid.UUID('6caabc94-4b2d-11ea-9106-645a049d591d')),
        ),
    ]
