# Generated by Django 2.2.6 on 2020-02-09 11:15

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('mediamanagement', '0041_auto_20200209_1645'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mediamessagemodel',
            name='uuid',
            field=models.TextField(default=uuid.UUID('7b32f406-4b2d-11ea-8bd2-645a049d591d')),
        ),
    ]
