# Generated by Django 2.2.6 on 2019-11-18 18:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accountapi', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ExtendedUserModel',
        ),
    ]
