# Generated by Django 2.2.6 on 2019-12-01 05:26

from django.db import migrations
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('accountapi', '0005_auto_20191128_0027'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofiles',
            name='phone',
            field=phonenumber_field.modelfields.PhoneNumberField(blank=True, help_text='Contact phone number', max_length=128, region=None),
        ),
    ]
