# Generated by Django 2.2.6 on 2019-12-01 05:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accountapi', '0006_auto_20191201_1056'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofiles',
            name='phone',
            field=models.TextField(),
        ),
    ]
