# Generated by Django 2.2.6 on 2020-02-08 23:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accountapi', '0007_auto_20191201_1105'),
    ]

    operations = [
        migrations.CreateModel(
            name='Counter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('multimedia_message_count', models.BigIntegerField(default=0)),
                ('text_message_count', models.BigIntegerField(default=0)),
                ('total_message_count', models.BigIntegerField(default=0)),
            ],
        ),
    ]
