# Generated by Django 2.2.6 on 2019-11-14 09:02

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MessageProcessModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.TextField()),
                ('from_who', models.TextField()),
                ('to_who', models.TextField()),
                ('message', models.TextField()),
                ('sent_status', models.BooleanField()),
                ('message_date_time', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
    ]
