# Generated by Django 2.2.7 on 2019-11-15 04:48

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('messageprocess', '0002_auto_20191114_2254'),
    ]

    operations = [
        migrations.AlterField(
            model_name='messageprocessmodel',
            name='message_uuid',
            field=models.TextField(default=uuid.UUID('2d5efbc2-0763-11ea-be8d-c42c03361ed0')),
        ),
    ]
