# Generated by Django 2.2.7 on 2019-11-18 10:00

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('messageprocess', '0004_auto_20191118_0541'),
    ]

    operations = [
        migrations.AlterField(
            model_name='messageprocessmodel',
            name='message_uuid',
            field=models.TextField(default=uuid.UUID('3c12c354-09ea-11ea-90a9-c42c03361ed0')),
        ),
    ]
