# Generated by Django 2.2.7 on 2019-11-18 10:04

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('messageprocess', '0005_auto_20191118_1000'),
    ]

    operations = [
        migrations.AlterField(
            model_name='messageprocessmodel',
            name='message_uuid',
            field=models.TextField(default=uuid.UUID('d7f8046e-09ea-11ea-b4cd-c42c03361ed0')),
        ),
    ]
