# Generated by Django 2.2.7 on 2019-11-18 10:20

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('messageprocess', '0006_auto_20191118_1004'),
    ]

    operations = [
        migrations.AlterField(
            model_name='messageprocessmodel',
            name='message_uuid',
            field=models.TextField(default=uuid.UUID('0b7e2776-09ed-11ea-86c9-c42c03361ed0')),
        ),
    ]
