# Generated by Django 2.2.6 on 2019-11-18 18:10

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('messageprocess', '0007_auto_20191118_1020'),
    ]

    operations = [
        migrations.AlterField(
            model_name='messageprocessmodel',
            name='message_uuid',
            field=models.TextField(default=uuid.UUID('a9c96912-0a2e-11ea-b6d4-645a049d591d')),
        ),
    ]
