# Generated by Django 2.2.6 on 2019-11-18 18:38

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('messageprocess', '0009_auto_20191119_0008'),
    ]

    operations = [
        migrations.AlterField(
            model_name='messageprocessmodel',
            name='message_uuid',
            field=models.TextField(default=uuid.UUID('9e63756e-0a32-11ea-a2dc-645a049d591d')),
        ),
    ]
