# Generated by Django 2.2.6 on 2019-11-18 19:36

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('messageprocess', '0011_auto_20191119_0012'),
    ]

    operations = [
        migrations.AlterField(
            model_name='messageprocessmodel',
            name='message_uuid',
            field=models.TextField(default=uuid.UUID('842be08c-0a3a-11ea-9c4b-645a049d591d')),
        ),
    ]
