# Generated by Django 2.2.6 on 2019-11-19 17:55

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('messageprocess', '0012_auto_20191119_0106'),
    ]

    operations = [
        migrations.AlterField(
            model_name='messageprocessmodel',
            name='message_uuid',
            field=models.TextField(default=uuid.UUID('bd961464-0af5-11ea-84df-645a049d591d')),
        ),
    ]
