# Generated by Django 2.2.6 on 2019-11-19 18:08

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('messageprocess', '0013_auto_20191119_2325'),
    ]

    operations = [
        migrations.AlterField(
            model_name='messageprocessmodel',
            name='message_uuid',
            field=models.TextField(default=uuid.UUID('8ceb5fac-0af7-11ea-ac07-645a049d591d')),
        ),
    ]
