# Generated by Django 2.2.7 on 2019-11-20 16:36

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('messageprocess', '0016_auto_20191120_1202'),
    ]

    operations = [
        migrations.AlterField(
            model_name='messageprocessmodel',
            name='message_uuid',
            field=models.TextField(default=uuid.UUID('e441eb88-0bb3-11ea-ab4a-645a049d591d')),
        ),
    ]
