# Generated by Django 2.2.6 on 2019-11-23 05:26

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('messageprocess', '0017_auto_20191120_2206'),
    ]

    operations = [
        migrations.AlterField(
            model_name='messageprocessmodel',
            name='message_uuid',
            field=models.TextField(default=uuid.UUID('c25da2ec-0db1-11ea-89ee-645a049d591d')),
        ),
    ]
