# Generated by Django 2.2.6 on 2019-11-23 05:27

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('messageprocess', '0018_auto_20191123_1056'),
    ]

    operations = [
        migrations.AlterField(
            model_name='messageprocessmodel',
            name='message_uuid',
            field=models.TextField(default=uuid.UUID('ebb33f2e-0db1-11ea-8dde-645a049d591d')),
        ),
    ]
