# Generated by Django 2.2.6 on 2019-11-24 18:47

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('messageprocess', '0020_auto_20191123_1059'),
    ]

    operations = [
        migrations.AlterField(
            model_name='messageprocessmodel',
            name='message_uuid',
            field=models.TextField(default=uuid.UUID('dfee9612-0eea-11ea-9f69-645a049d591d')),
        ),
    ]
