# Generated by Django 2.2.6 on 2019-11-24 19:02

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('messageprocess', '0021_auto_20191125_0017'),
    ]

    operations = [
        migrations.AlterField(
            model_name='messageprocessmodel',
            name='message_uuid',
            field=models.TextField(default=uuid.UUID('ee82d1e2-0eec-11ea-b41f-645a049d591d')),
        ),
    ]
