# Generated by Django 2.2.6 on 2019-11-27 18:28

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('messageprocess', '0023_auto_20191127_2340'),
    ]

    operations = [
        migrations.AlterField(
            model_name='messageprocessmodel',
            name='message_uuid',
            field=models.TextField(default=uuid.UUID('bc61eab8-1143-11ea-b1a8-645a049d591d')),
        ),
    ]
