# Generated by Django 2.2.6 on 2019-11-27 18:49

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('messageprocess', '0025_auto_20191128_0001'),
    ]

    operations = [
        migrations.AlterField(
            model_name='messageprocessmodel',
            name='message_uuid',
            field=models.TextField(default=uuid.UUID('9d6acc7a-1146-11ea-b382-645a049d591d')),
        ),
    ]
