# Generated by Django 2.2.6 on 2019-11-27 18:57

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('messageprocess', '0026_auto_20191128_0019'),
    ]

    operations = [
        migrations.AlterField(
            model_name='messageprocessmodel',
            name='message_uuid',
            field=models.TextField(default=uuid.UUID('b5f00e5e-1147-11ea-8b44-645a049d591d')),
        ),
    ]
