# Generated by Django 2.2.6 on 2019-11-30 16:43

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('messageprocess', '0027_auto_20191128_0027'),
    ]

    operations = [
        migrations.AlterField(
            model_name='messageprocessmodel',
            name='message_uuid',
            field=models.TextField(default=uuid.UUID('7e69e00c-1390-11ea-836c-645a049d591d')),
        ),
    ]
