# Generated by Django 2.2.6 on 2019-12-01 05:26

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('messageprocess', '0028_auto_20191130_2213'),
    ]

    operations = [
        migrations.AlterField(
            model_name='messageprocessmodel',
            name='message_uuid',
            field=models.TextField(default=uuid.UUID('259f96f8-13fb-11ea-a1ef-645a049d591d')),
        ),
    ]
