# Generated by Django 2.2.6 on 2019-12-01 05:35

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('messageprocess', '0029_auto_20191201_1056'),
    ]

    operations = [
        migrations.AlterField(
            model_name='messageprocessmodel',
            name='message_uuid',
            field=models.TextField(default=uuid.UUID('5541fa06-13fc-11ea-b31e-645a049d591d')),
        ),
    ]
