# Generated by Django 2.2.6 on 2019-12-30 09:06

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('messageprocess', '0031_auto_20191201_1118'),
    ]

    operations = [
        migrations.AlterField(
            model_name='messageprocessmodel',
            name='message_uuid',
            field=models.TextField(default=uuid.UUID('a2b037d0-2ae3-11ea-a645-0a2555865e12')),
        ),
    ]
