# Generated by Django 2.2.6 on 2020-02-09 00:51

from django.db import migrations, models
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('messageprocess', '0032_auto_20191230_0906'),
    ]

    operations = [
        migrations.CreateModel(
            name='MessageCounter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text_message_count', models.BigIntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='MessageListModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message_uuid', models.TextField(default=uuid.UUID('480358dc-4ad6-11ea-94c0-645a049d591d'))),
                ('from_whom', models.TextField(blank=True, null=True)),
                ('to_whom', models.TextField(blank=True, null=True)),
                ('body', models.TextField(blank=True, null=True)),
                ('message_type', models.TextField(blank=True, null=True)),
                ('file_url', models.TextField(blank=True, null=True)),
                ('content_type', models.TextField(blank=True, null=True)),
                ('sent_status', models.BooleanField(default=True)),
                ('message_date_time', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.AlterField(
            model_name='messageprocessmodel',
            name='message_uuid',
            field=models.TextField(default=uuid.UUID('4802bca8-4ad6-11ea-b87c-645a049d591d')),
        ),
    ]
