# Generated by Django 2.2.6 on 2020-02-09 11:15

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('messageprocess', '0033_auto_20200209_0621'),
    ]

    operations = [
        migrations.AlterField(
            model_name='messagelistmodel',
            name='message_uuid',
            field=models.TextField(default=uuid.UUID('6ca9d264-4b2d-11ea-ad91-645a049d591d')),
        ),
        migrations.AlterField(
            model_name='messagelistmodel',
            name='sent_status',
            field=models.TextField(default=True),
        ),
        migrations.AlterField(
            model_name='messageprocessmodel',
            name='message_uuid',
            field=models.TextField(default=uuid.UUID('6ca90f26-4b2d-11ea-9db1-645a049d591d')),
        ),
    ]
