# Generated by Django 2.2.6 on 2020-02-09 11:15

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('messageprocess', '0034_auto_20200209_1645'),
    ]

    operations = [
        migrations.AlterField(
            model_name='messagelistmodel',
            name='message_uuid',
            field=models.TextField(default=uuid.UUID('7b3230dc-4b2d-11ea-923d-645a049d591d')),
        ),
        migrations.AlterField(
            model_name='messagelistmodel',
            name='sent_status',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='messageprocessmodel',
            name='message_uuid',
            field=models.TextField(default=uuid.UUID('7b3194a6-4b2d-11ea-bfbf-645a049d591d')),
        ),
    ]
