# Generated by Django 2.2.6 on 2020-03-11 10:27

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('messageprocess', '0035_auto_20200209_1645'),
    ]

    operations = [
        migrations.AlterField(
            model_name='messagelistmodel',
            name='message_uuid',
            field=models.TextField(default=uuid.UUID('f35ae9e7-6382-11ea-ba79-02e32cf20e1c')),
        ),
        migrations.AlterField(
            model_name='messageprocessmodel',
            name='message_uuid',
            field=models.TextField(default=uuid.UUID('f35ae9e6-6382-11ea-ba79-02e32cf20e1c')),
        ),
    ]
