# Generated by Django 2.2.6 on 2020-03-12 18:53

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('messageprocess', '0036_auto_20200311_1027'),
    ]

    operations = [
        migrations.AlterField(
            model_name='messagelistmodel',
            name='message_uuid',
            field=models.TextField(default=uuid.UUID('d49a1f3f-6492-11ea-b0bd-0a6bc245c18e')),
        ),
        migrations.AlterField(
            model_name='messageprocessmodel',
            name='message_uuid',
            field=models.TextField(default=uuid.UUID('d49a1f3e-6492-11ea-b0bd-0a6bc245c18e')),
        ),
    ]
